import Head from 'next/head'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Mark's Portfolio </title>
        <meta name="description" content="Generated by Mark Aguilar" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main>
        <h1>My Portfolio</h1>
      </main>
        
    </div>
  )
}
